# Generated by Django 6.0.7 on 2026-07-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraLog',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(max_length=10)),
                ('campo_modificado', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_antiguo', models.CharField(blank=True, max_length=160, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'bitacora_log',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fono_contacto', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_credito', models.IntegerField()),
                ('saldo_deudor', models.IntegerField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('fono_contacto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='EstadoCredito',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'estado_credito',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fono_contacto', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_chofer', models.CharField(max_length=30)),
                ('fono_contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'transportista',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('nombre_bodega', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ubicacion_bodega', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'bodega',
                'unique_together': {('nombre_bodega', 'ubicacion_bodega')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaCategorizaProducto',
            fields=[
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.categoria')),
            ],
            options={
                'db_table': 'categoria_categoriza_producto',
            },
        ),
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.cliente')),
                ('razon_social', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente_empresa',
            },
        ),
        migrations.CreateModel(
            name='ClientePersona',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.cliente')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente_persona',
            },
        ),
        migrations.CreateModel(
            name='AbonoCredito',
            fields=[
                ('id_abono', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=20)),
                ('rut_cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.PROTECT, to='myapp.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='myapp.empleado')),
            ],
            options={
                'db_table': 'abono_credito',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='myapp.estadocredito'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_de_emision', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('total_bruto', models.IntegerField()),
                ('es_credito', models.BooleanField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='myapp.empleado')),
                ('rut_cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.PROTECT, to='myapp.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=15)),
                ('folio', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='myapp.empleado')),
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='myapp.pedido')),
            ],
            options={
                'db_table': 'documento_tributario',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion_entrega', models.CharField(max_length=150)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado_entrega', models.CharField(max_length=20)),
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='myapp.rol'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('es_granel', models.BooleanField()),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', through='myapp.CategoriaCategorizaProducto', to='myapp.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='categoriacategorizaproducto',
            name='sku',
            field=models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='myapp.producto'),
        ),
        migrations.CreateModel(
            name='DespachoTransportista',
            fields=[
                ('id_despacho', models.OneToOneField(db_column='id_despacho', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.despacho')),
                ('patente_vehiculo', models.CharField(max_length=6)),
                ('id_transportista', models.ForeignKey(db_column='id_transportista', on_delete=django.db.models.deletion.PROTECT, to='myapp.transportista')),
            ],
            options={
                'db_table': 'despacho_transportista',
            },
        ),
        migrations.CreateModel(
            name='BodegaAlmacenaProducto',
            fields=[
                ('nombre_bodega', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ubicacion_bodega', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
            options={
                'db_table': 'bodega_almacena_producto',
                'unique_together': {('nombre_bodega', 'ubicacion_bodega', 'sku')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoriacategorizaproducto',
            unique_together={('id_categoria', 'sku')},
        ),
        migrations.CreateModel(
            name='PedidoContieneProducto',
            fields=[
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.pedido')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.PROTECT, to='myapp.producto')),
            ],
            options={
                'db_table': 'pedido_contiene_producto',
                'unique_together': {('id_pedido', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProveedorSuministraProducto',
            fields=[
                ('rut_proveedor', models.ForeignKey(db_column='rut_proveedor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.proveedor')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento_lote', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('sku_producto', models.ForeignKey(db_column='sku_producto', on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
            options={
                'db_table': 'proveedor_suministra_producto',
                'unique_together': {('rut_proveedor', 'sku_producto', 'fecha')},
            },
        ),
    ]
