# Generated by Django 6.0.7 on 2026-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorsuministraproducto',
            name='nombre_bodega',
            field=models.CharField(default='Principal', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedorsuministraproducto',
            name='ubicacion_bodega',
            field=models.CharField(default='Test', max_length=15),
            preserve_default=False,
        ),
    ]
